<?php

namespace ContainerAZvUWiw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AfcRK_NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AfcRK.N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AfcRK.N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'parseGedcomToModel' => ['privates', 'App\\Parser\\ParseGedcomToModel', 'getParseGedcomToModelService', true],
            'serializeModel' => ['privates', 'App\\Serializer\\SerializeModel', 'getSerializeModelService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'parseGedcomToModel' => 'App\\Parser\\ParseGedcomToModel',
            'serializeModel' => 'App\\Serializer\\SerializeModel',
            'em' => '?',
        ]);
    }
}
