<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFFnMgh5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFFnMgh5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFFnMgh5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFFnMgh5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFFnMgh5\App_KernelDevDebugContainer([
    'container.build_hash' => 'FFnMgh5',
    'container.build_id' => 'f4e29453',
    'container.build_time' => 1719910020,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFFnMgh5');
