<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ6UC1wr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ6UC1wr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ6UC1wr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ6UC1wr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ6UC1wr\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q6UC1wr',
    'container.build_id' => 'b4786439',
    'container.build_time' => 1714837389,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ6UC1wr');
